import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:y
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5bFmKLd7NArUgESAu617gUcEhUQjRHA',
    appId: '1:183890975725:web:d943e54b29c5f2d77265e4',
    messagingSenderId: '183890975725',
    projectId: 'chat-app-1355b',
    authDomain: 'chat-app-1355b.firebaseapp.com',
    storageBucket: 'chat-app-1355b.firebasestorage.app',
    measurementId: 'G-V15DMC9HTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIjWh-rpsL_BU5QKHmFdqxtUNbgOVOU5Q',
    appId: '1:183890975725:android:cbe22a1d88b7561a7265e4',
    messagingSenderId: '183890975725',
    projectId: 'chat-app-1355b',
    storageBucket: 'chat-app-1355b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8B8fzdDR6BZ0Ju03hHGHJqOsJWfL5J7A',
    appId: '1:183890975725:ios:0dd7063ac556d3d37265e4',
    messagingSenderId: '183890975725',
    projectId: 'chat-app-1355b',
    storageBucket: 'chat-app-1355b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8B8fzdDR6BZ0Ju03hHGHJqOsJWfL5J7A',
    appId: '1:183890975725:ios:0dd7063ac556d3d37265e4',
    messagingSenderId: '183890975725',
    projectId: 'chat-app-1355b',
    storageBucket: 'chat-app-1355b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW5bFmKLd7NArUgESAu617gUcEhUQjRHA',
    appId: '1:183890975725:web:6c50f821cfa30e287265e4',
    messagingSenderId: '183890975725',
    projectId: 'chat-app-1355b',
    authDomain: 'chat-app-1355b.firebaseapp.com',
    storageBucket: 'chat-app-1355b.firebasestorage.app',
    measurementId: 'G-PBXKX5S73V',
  );
}
